# Generated by Django 3.2.6 on 2021-09-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20210903_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='shipping_address2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
