# Generated by Django 3.2.6 on 2021-09-03 16:06

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_alter_address_shipping_address2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='shipping_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
